---
title: "EDA"
format: 
  html:
    toc: true
    toc-depth: 5
    number-sections: true
    code-fold: true
---

## パイプライン読み込み

```{r echo=FALSE}
library(targets)
tar_load_globals()
tar_load_everything()

library(DT)
library(gtsummary)
library(patchwork)
```

## 変数の把握

### 学習データ

```{r}
skim(df_train)
```

### テストデータ

```{r}
skim(df_test)
```

### 変数名の確認

```{r}
dplyr::setdiff(colnames(df_train), colnames(df_test))
```

## 変数の調査

### ユニークレコードの把握

-   間隔尺度・比例尺度以外に、数値ラベル化された変数があるかどうかを確認するため
-   ユニーク数12以下はカテゴリと扱って良さそう

```{r}
df_Check_unique_record_train |> 
  gt::gt()

df_Check_unique_record_test |> 
  gt::gt()
```

### サマリー

#### 学習データ

```{r}
gts_df_train
```

#### テストデータ

```{r}
gts_df_test
```

### 欠損値の数

#### 学習データ

```{r}
df_Check_NA_train |> 
  dplyr::mutate(across(matches("Ratio"), .fns = ~round(.x, digits = 1))) |> 
  gt::gt() 
  
```

#### テストデータ

```{r}
df_Check_NA_test |> 
  dplyr::mutate(Ratio = round(Ratio, digits = 1)) |> 
  gt::gt()
```

## 変数の視覚化

### 基礎情報 - 数値

```{r}
(g_age + g_bmi) / (g_height + g_weight)
```

### 基礎情報 - カテゴリ

```{r}
#| fig-height: 9

g_situation_1 / g_situation_2 / g_gender / g_ethnicity
```

### ICU

#### ICU ID

```{r}
g_icu_id
```

#### ICU 1

```{r}
g_icu_1
```

#### ICU 2

```{r}
g_icu_2
```

#### ICU 3

```{r}
g_icu_3
```

#### ICU 4

```{r}
#| fig-height: 6

g_icu_4 / g_icu_4_log
```

#### ICU 5

```{r}
g_icu_5
```

#### ICU 6

```{r}
g_icu_6
```

#### ICU 7

```{r}
g_icu_7
```

#### ICU 8

```{r}
g_icu_8
```

### グラスゴー・コーマ・スケール

```{r}
#| fig-height: 9

g_GSC_1 / g_GSC_2 / g_GSC_3 / g_GSC_4
```

### 生理機能

```{r}
#| fig-height: 12

g_heart_rate / g_blood_oxy / g_arterial_pressure / g_respiratory_rate / g_temp
```

### 変数V

```{r}
#| fig-height: 3
#| 
for(i in 1:length(g_V_all)){
  plot(g_V_all[[i]])
}
```

### 変数W

```{r}
#| fig-height: 3
#| 
for(i in 1:length(g_W_all)){
  plot(g_W_all[[i]])
}
```

### 変数X

```{r}
#| fig-height: 3
#| 
for(i in 1:length(g_X_all)){
  plot(g_X_all[[i]])
}
```